### ISSUE TITLE
failure on epoch change

### ISSUE THREAD

**Issue by nerdralph** [genesismining/sgminer-gm#15]
Just happened with a 4GB R9 290.  2 R9 380s (4GB) controlled by the same sgminer instance handled the transition fine.  Running v5.4.0 on Ubuntu 14.04 with fglrx drivers.  Same GPU is mining fine after restarting sgminer.  Error message:
[14:01:00] Error -2: Setting args for the DAG kernel and/or executing it.
[14:01:00] Error: clSetKernelArg of all params failed.
[14:01:00] GPU 0 failure, disabling!

**Comment by wolf9466** [comment]
That's... not a lot to go on. Do you have a debug log?

**Comment by nerdralph** [comment]
Sorry, no debug log.  I've occasionally seen the same kind of thing on Genoil's miner too, but it hasn't been a priority to fix.  My first thought is some sort of race condition with clReleaseMemObject since the docs suggest it operates asynchronously.  If you aren't already doing it, I'd suggest waiting several ms between the clRelease and clCreate calls.
