### ISSUE TITLE
sgminer will not start on clean install win 64bit full updated

### ISSUE THREAD

**Issue by Nightworker88** [genesismining/sgminer-gm#24]
Since two weeks i try to use sgminer

i have one rig where i stopped updates about half year ago, there sgminer works.

all other rigs, like yesterday - tried a completly new install win 10 64 bit all updates, no chance to start sgminer, - start and close immedatly- but all other miners work (all claymore, gpu, cpu, nheqminer)!?

and the problem for sgminer i cannot find a kind of log file to see what happens.

then i tried ccminer: strange: start, close , say one win .dll missing - but this dll comes with cc, also ms has a command line which auto repairs these dlls--all ok!

get crazy! surly made min. 5 fresh installs with complete different hardware, mobo,ram,ssd, cpu, gpu!!  

always same, claymore ......work -sgminer start and close immediatly!

i am the only one have this problem? and also in www i could not find anything helpful

somebody have any ideas? would be great!

**Comment by magick777** [comment]
On Windows, the binary is compiled with ADL support, and I had to make "--no-adl" the first command line switch to get it to start, or even to reply to a --ndevs. Order of switches matters.

That just led me to another problem, which I've raised as a separate issue, so you might want to try an older sgminer binary. I'll update if that gets me anywhere.

As for seeing the output, you can always run your batch file from a command prompt. Personally I have the sgminer-gm folder in my Desktop, in which I created a batch file for my startup incantations, and while testing I open up a command prompt, cd to the folder and run the batch file there to see the output.

**Comment by Nightworker88** [comment]
hello,

thanks for answer, i will check it 

i tried before some different older sgminer, which one would you prefer to use ?

**Comment by jch9678** [comment]
Before you try an older sgminer, use    --gpu-platform 1    like magick777 suggested.  That should fix it.  I have identical machines, one needs --gpu-platform 1 for some reason.

**Comment by tpruvot** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Khronos\OpenCL\Vendors

**Comment by Nightworker88** [comment]
thanks

i will check it next time, must work now

**Comment by Nightworker88** [comment]
just was nervous -wanted give a try for five minutes

two rigs - added just  --gpu-platform 1 - both worked!!
thak you all so much, two weeks of i do not know how much hours i spent

now can look what will happen next, hope all other rigs will also start

now must work

thanks so much!!!!!!

**Comment by jch9678** [comment]
That's great for you.  I've been lazy and using claymore's miners and completely forgot that I needed that parameter on one of my machines until magick777 reminded me of it.  

@tpruvot can you change platform numbers in those keys or just check?

**Comment by tpruvot** [comment]
you can rename one to disable it, it works without restart

**Comment by ZeroASIC** [comment]
This bug is fixed in the latest release.  I think it can be closed.
