### ISSUE TITLE
OpenCL Not Found 

### ISSUE THREAD

**Issue by joker5bb** [genesismining/sgminer-gm#26]

**Comment by int03h** [comment]
No sure if you have installed the supporting libs from the OS ? Generally I do a apt-cache search and look for icd , ocl / opencl, dev and lib and install all of them ... 

for example but not exclusively : 

dpkg -l | grep opencl
ii  amdgpu-pro-libopencl-dev:amd64             16.30.3-315407                                amd64        AMD OpenCL ICD Loader library
ii  amdgpu-pro-libopencl1:amd64                16.30.3-315407                                amd64        AMD OpenCL ICD Loader library
ii  amdgpu-pro-opencl-icd:amd64                16.30.3-315407                                amd64        non-free AMD OpenCL ICD Loaders
**ii  ocl-icd-libopencl1:amd64                   2.2.8-1                                       amd64        Generic OpenCL ICD Loader**
**ii  opencl-headers                             2.0~svn32091-2                                all          OpenCL (Open Computing Language) header files**

**Comment by joker5bb** [comment]
No its not a package you download from 
http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/

I have everything done correctly, you can clearly see the files in that directory

**Comment by joker5bb** [comment]
I have packages mesa-opencl-icd & opencl-headers installed and same issue occurs

**Comment by joker5bb** [comment]
I ignored the opencl error and compiled anyway

sgminer-sgminer.o: In function `set_current_pool':
sgminer.c:(.text+0x82ce): undefined reference to `clReleaseMemObject'
sgminer-driver-opencl.o: In function `opencl_thread_shutdown':
driver-opencl.c:(.text+0x7b): undefined reference to `clFinish'
driver-opencl.c:(.text+0x84): undefined reference to `clReleaseMemObject'
driver-opencl.c:(.text+0x8d): undefined reference to `clReleaseMemObject'
driver-opencl.c:(.text+0x9e): undefined reference to `clReleaseMemObject'
driver-opencl.c:(.text+0xaf): undefined reference to `clReleaseMemObject'
driver-opencl.c:(.text+0xc0): undefined reference to `clReleaseMemObject'
sgminer-driver-opencl.o:driver-opencl.c:(.text+0xce): more undefined references to `clReleaseMemObject' follow
sgminer-driver-opencl.o: In function `opencl_thread_shutdown':
driver-opencl.c:(.text+0xd9): undefined reference to `clReleaseKernel'
driver-opencl.c:(.text+0xf9): undefined reference to `clReleaseKernel'
driver-opencl.c:(.text+0x10e): undefined reference to `clReleaseProgram'
driver-opencl.c:(.text+0x117): undefined reference to `clReleaseCommandQueue'
driver-opencl.c:(.text+0x11f): undefined reference to `clReleaseContext'
sgminer-driver-opencl.o: In function `opencl_thread_init':
driver-opencl.c:(.text+0x1d8): undefined reference to `clEnqueueWriteBuffer'
sgminer-driver-opencl.o: In function `opencl_scanhash':
driver-opencl.c:(.text+0xca9): undefined reference to `clEnqueueNDRangeKernel'
driver-opencl.c:(.text+0xd27): undefined reference to `clEnqueueNDRangeKernel'
driver-opencl.c:(.text+0xeeb): undefined reference to `clEnqueueWriteBuffer'
driver-opencl.c:(.text+0xf1a): undefined reference to `clFinish'
driver-opencl.c:(.text+0xf49): undefined reference to `clEnqueueNDRangeKernel'
driver-opencl.c:(.text+0xf8b): undefined reference to `clEnqueueNDRangeKernel'
driver-opencl.c:(.text+0xfc2): undefined reference to `clEnqueueNDRangeKernel'
driver-opencl.c:(.text+0x1015): undefined reference to `clEnqueueReadBuffer'
driver-opencl.c:(.text+0x104c): undefined reference to `clFinish'
driver-opencl.c:(.text+0x10b9): undefined reference to `clEnqueueReadBuffer'
driver-opencl.c:(.text+0x10e0): undefined reference to `clFinish'
driver-opencl.c:(.text+0x1135): undefined reference to `clEnqueueWriteBuffer'
driver-opencl.c:(.text+0x1185): undefined reference to `clFinish'
driver-opencl.c:(.text+0x12ed): undefined reference to `clEnqueueReadBuffer'
driver-opencl.c:(.text+0x14a4): undefined reference to `clSetKernelArg'
driver-opencl.c:(.text+0x14ef): undefined reference to `clEnqueueNDRangeKernel'
sgminer-ocl.o: In function `get_opencl_version':
ocl.c:(.text+0x2f): undefined reference to `clGetDeviceInfo'
sgminer-ocl.o: In function `get_opencl_platform':
ocl.c:(.text+0x1a9): undefined reference to `clGetPlatformIDs'
ocl.c:(.text+0x21e): undefined reference to `clGetPlatformIDs'
sgminer-ocl.o: In function `clDevicesNum':
ocl.c:(.text+0x343): undefined reference to `clGetPlatformInfo'
ocl.c:(.text+0x37b): undefined reference to `clGetPlatformInfo'
ocl.c:(.text+0x39d): undefined reference to `clGetPlatformInfo'
ocl.c:(.text+0x3bd): undefined reference to `clGetDeviceIDs'
ocl.c:(.text+0x479): undefined reference to `clGetDeviceIDs'
ocl.c:(.text+0x4a8): undefined reference to `clGetDeviceInfo'
sgminer-ocl.o: In function `initCl':
ocl.c:(.text+0x645): undefined reference to `clGetDeviceIDs'
ocl.c:(.text+0x6c1): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0x70b): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0x7f7): undefined reference to `clCreateContextFromType'
ocl.c:(.text+0x84e): undefined reference to `clCreateCommandQueue'
ocl.c:(.text+0x890): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0x8db): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0x934): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0x9d9): undefined reference to `clGetDeviceInfo'
ocl.c:(.text+0xe97): undefined reference to `clCreateKernel'
ocl.c:(.text+0xfe8): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1032): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1067): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x10b1): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1116): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1184): undefined reference to `clCreateCommandQueue'
ocl.c:(.text+0x1494): undefined reference to `clCreateKernel'
ocl.c:(.text+0x1618): undefined reference to `clCreateKernel'
ocl.c:(.text+0x17d9): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x180f): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1a09): undefined reference to `clCreateKernel'
ocl.c:(.text+0x1b67): undefined reference to `clCreateKernel'
ocl.c:(.text+0x1bbb): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1bfd): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x1da0): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x208c): undefined reference to `clCreateBuffer'
ocl.c:(.text+0x20c6): undefined reference to `clCreateBuffer'
sgminer-ocl.o:ocl.c:(.text+0x2100): more undefined references to `clCreateBuffer' follow
sgminer-ocl.o: In function `initCl':
ocl.c:(.text+0x2417): undefined reference to `clSetKernelArg'
ocl.c:(.text+0x2437): undefined reference to `clSetKernelArg'
ocl.c:(.text+0x2454): undefined reference to `clSetKernelArg'
ocl.c:(.text+0x2474): undefined reference to `clSetKernelArg'
ocl.c:(.text+0x2494): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_equihash_kernel':
algorithm.c:(.text+0x190): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x1ca): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x296): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2b0): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2d5): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2ef): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x312): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x346): undefined reference to `clEnqueueNDRangeKernel'
algorithm.c:(.text+0x391): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3b3): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3e2): undefined reference to `clEnqueueNDRangeKernel'
algorithm.c:(.text+0x410): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x42a): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x444): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x46a): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x494): undefined reference to `clEnqueueNDRangeKernel'
algorithm.c:(.text+0x4b8): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x4ea): undefined reference to `clEnqueueNDRangeKernel'
algorithm.c:(.text+0x519): undefined reference to `clEnqueueNDRangeKernel'
sgminer-algorithm.o: In function `queue_cryptonight_kernel':
algorithm.c:(.text+0x605): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x620): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x639): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x652): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x66b): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x683): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x69d): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_yescrypt_multikernel':
algorithm.c:(.text+0x9c0): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x9e2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xa03): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xa1b): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xa33): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xa4b): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0xa63): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_credits_kernel':
algorithm.c:(.text+0xcb7): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0xcd1): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xcea): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xd02): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xd26): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_neoscrypt_kernel':
algorithm.c:(.text+0xdef): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0xe09): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xe22): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xe3b): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xe55): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_scrypt_kernel':
algorithm.c:(.text+0xf21): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0xf3d): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xf58): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xf73): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xf90): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0xfad): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0xfc8): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_blake_kernel':
algorithm.c:(.text+0x1043): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x105d): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1081): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x10a5): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x10c9): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x10ed): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1111): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_whirlcoin_kernel':
algorithm.c:(.text+0x1277): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x1291): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x12a9): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x12c2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x12d7): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x12ec): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1305): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_lyra2rev2_kernel':
algorithm.c:(.text+0x13ca): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x13e3): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1406): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1429): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x144c): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x146f): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1492): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_lyra2re_kernel':
algorithm.c:(.text+0x16d7): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x16f0): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1714): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1738): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x175c): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1780): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x17a4): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_fresh_kernel':
algorithm.c:(.text+0x19a7): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x19c1): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x19d9): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x19f2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1a07): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1a1c): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1a31): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_bitblock_kernel':
algorithm.c:(.text+0x1b17): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x1b31): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1b49): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1b62): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1b77): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1b8c): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1ba1): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_x14_old_kernel':
algorithm.c:(.text+0x1d47): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x1d61): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1d79): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1d92): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1da7): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1dbc): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1dd1): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_x14_kernel':
algorithm.c:(.text+0x1f57): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x1f71): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1f89): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1fa2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1fb7): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x1fcc): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x1fe1): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_marucoin_mod_kernel':
algorithm.c:(.text+0x2177): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x2191): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x21a9): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x21c2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x21d7): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x21ec): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x2201): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_maxcoin_kernel':
algorithm.c:(.text+0x2353): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x236d): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2386): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_sph_kernel':
algorithm.c:(.text+0x240b): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x2425): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x243e): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2456): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_yescrypt_kernel':
algorithm.c:(.text+0x24eb): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x2505): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x251e): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2537): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2553): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x256f): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x2589): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_pluck_kernel':
algorithm.c:(.text+0x261b): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x2635): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x264e): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2667): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x2681): undefined reference to `clSetKernelArg'
sgminer-algorithm.o: In function `queue_whirlpoolx_kernel':
algorithm.c:(.text+0x283d): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x2859): more undefined references to `clSetKernelArg' follow
sgminer-algorithm.o: In function `queue_ethash_kernel':
algorithm.c:(.text+0x312d): undefined reference to `clReleaseMemObject'
algorithm.c:(.text+0x3167): undefined reference to `clCreateBuffer'
algorithm.c:(.text+0x31a8): undefined reference to `clCreateBuffer'
algorithm.c:(.text+0x3209): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3223): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3249): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3265): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3289): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x32cb): undefined reference to `clEnqueueNDRangeKernel'
algorithm.c:(.text+0x32dc): undefined reference to `clFinish'
algorithm.c:(.text+0x32e6): undefined reference to `clReleaseMemObject'
algorithm.c:(.text+0x33ae): undefined reference to `clReleaseMemObject'
algorithm.c:(.text+0x358f): undefined reference to `clEnqueueWriteBuffer'
algorithm.c:(.text+0x35ab): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x35c6): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x35e2): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x35fc): undefined reference to `clSetKernelArg'
algorithm.c:(.text+0x3621): undefined reference to `clSetKernelArg'
sgminer-algorithm.o:algorithm.c:(.text+0x363b): more undefined references to `clSetKernelArg' follow
ocl/sgminer-build_kernel.o: In function `build_opencl_kernel':
build_kernel.c:(.text+0x42b): undefined reference to `clCreateProgramWithSource'
build_kernel.c:(.text+0x470): undefined reference to `clBuildProgram'
build_kernel.c:(.text+0x50a): undefined reference to `clGetProgramBuildInfo'
build_kernel.c:(.text+0x541): undefined reference to `clGetProgramBuildInfo'
ocl/sgminer-build_kernel.o: In function `save_opencl_kernel':
build_kernel.c:(.text+0x5d6): undefined reference to `clGetProgramInfo'
build_kernel.c:(.text+0x5f9): undefined reference to `clGetProgramInfo'
build_kernel.c:(.text+0x687): undefined reference to `clGetProgramInfo'
ocl/sgminer-binary_kernel.o: In function `load_opencl_binary_kernel':
binary_kernel.c:(.text+0xe7): undefined reference to `clCreateProgramWithBinary'
binary_kernel.c:(.text+0x12a): undefined reference to `clBuildProgram'
binary_kernel.c:(.text+0x16c): undefined reference to `clGetProgramBuildInfo'
binary_kernel.c:(.text+0x1a1): undefined reference to `clGetProgramBuildInfo'
binary_kernel.c:(.text+0x1d5): undefined reference to `clReleaseProgram'
collect2: error: ld returned 1 exit status
Makefile:854: recipe for target 'sgminer' failed
make[2]: *** [sgminer] Error 1
make[2]: Leaving directory '/home/user/sgminer-gm'
Makefile:1721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/sgminer-gm'
Makefile:663: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by papaiatis** [comment]
I installed both `ocl-icd-libopencl1` and `opencl-headers` but I'm still getting this error:

`./configure CFLAGS="-O3 -Wall -march=native"`
```
Configuration Options Summary:

  Use git version......: yes
  libcurl(GBT+getwork).: Enabled: -lcurl
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: NOT FOUND. GPU mining support DISABLED
configure: error: OpenCL not found
```

**Comment by int03h** [comment]
Take what you like from it .. usually everything works fine once I do this: 
`apt-get install -y make build-essential software-properties-common curl wget git g++ binutils file       \
        zlib1g-dev libedit-dev automake autoconf dh-autoreconf opencl-headers libcurl4-openssl-dev       \
        pkg-config libtool libncurses5-dev ocl-icd-dev ocl-icd-opencl-dev ocl-icd-libopencl1 libpci-dev  \
        libvdpau1 libjansson*
`

ln -s /opt/AMDAPPSDK-3.0/include/CL /usr/include
ln -s /opt/AMDAPPSDK-3.0/lib/x86_64/* /usr/lib/

**Comment by divious1** [comment]
for what is worth this ended working for me on ethos: https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS#33-configure-sgminer-source-code-for-compilation-and-linking

**Comment by kewur** [comment]
I had to manually put the libOpenCL.so in the sdk folder to /usr/lib for it to find OpenCL

**Comment by iobond** [comment]
@int03h  you totally save my life. thank you
