### ISSUE TITLE
SGMiner-GM 5.5.5 

### ISSUE THREAD

**Issue by aaronsace** [genesismining/sgminer-gm#29]
You've not attached the windows release? 
The description has gone now, is there something wrong with it?

**Comment by NaN-git** [comment]
Yes, we are aware of this and we will compile a Windows binary one as soon as possible.

**Comment by aaronsace** [comment]
Nice, was going to get it hooked up tonight.

**Comment by OhGodAGirl** [comment]
The windows release will take a bit, @wolf9466 and I are both travelling so we have to recompile our toolchains, etc. I'll aim for tonight, @aaronsace but no promises.

**Comment by aaronsace** [comment]
Cheers @OhGodAGirl, that's great news.

**Comment by NaN-git** [comment]
Working binaries are uploaded.
