### ISSUE TITLE
sgminer 5.5.5 breaks GPU monitoring support

### ISSUE THREAD

**Issue by joker5bb** [genesismining/sgminer-gm#31]
Are we not supposed to include the ADL files now because sgminer 5.5.4 monitoring worked with ADL files for AMDGPU opencl 16.60

**Comment by NaN-git** [comment]
I don't know what you are implying. It works with and without ADL headers. Just checkout master.

**Comment by jramos** [comment]
It works for me, but only when I start sgminer as root.

**Comment by megacrypto** [comment]
same here ... works only when started with root

**Comment by OhGodAGirl** [comment]
SGMiner-GM must be started with root permissions for GPU monitoring of any kind; closing this issue, will put this in the README.md for new users.
