### ISSUE TITLE
API Re-Work

### ISSUE THREAD

**Issue by DominiLux** [genesismining/sgminer-gm#37]
I forked this to more easily follow this project a while back and spent some time studying the code.  I noticed others making suggestions for a GUI to interface with the application.  While the API is nice it lacks a lot of capabilities.  Therefore, I have been working on revamping the API to not only provide all of the information the console app provides (When it's using ncurses) but also to allow real time control of all the existing features that the can be altered dynamically on the fly.  During the rebuild of the API I will do it in such a way that each API subroutine is located in it's own .c file for orginizational purposes.  The api will have a master.c file that parses and calls the appropriate functions.  This will allow for easier additions to the api by adding a parsing instruction in the api master file and the code in a new .c file for the added feature.  Once the entire CLI (Curses) interface is 100% API compatible it will open a doorway to creating very sharp looking GUI's in C# (My favorite for GUI development because of it's cross compatibility).  The GUI can also be designed in such a way to manage all the machines within a subnet but right now getting the API polished to where it will function as a communications protocol to a GUI (Or web interface) is most important.

What would be the best way for me to proceed with this?  I can re-fork the repository so that I can keep it's code current with sgminer-gm to be merged into your main project once completed.  While under development there would be far too many pull requests for you to manage because the API, as it stands right now is a sloppy mess, needs a lot of changes.

Let me know your thoughts...  Thanks.

One Suggestion: If anyone is knowledgeable on the Vulkan API I would love to see a modular Spir-V kernel implementation the same way OpenCL is integrated.  In fact if everything where moved over to Vulkan it would become 100% cross compatible across all operating systems and all GPU's.  That's just a thought tho.  My private miner uses Vulkan and I will just say that I'm getting close to 2X OpenCL's hash-rate but it's been extremely hardware optimized.  My private miner was written in C++ tho so its code is not directly compatible with this miner due to my heavy use of classes and custom vector structures.

**Comment by jch9678** [comment]
Which algos are you getting 2x the hashrate?

**Comment by DominiLux** [comment]
@jch9678 any of them can be heavily optimized when you utilize more modern tool chains that allow bare metal manipulation of the GPU.  OpenCL has become a bloated mess and is on it's way to being deprecated.  Optimizing an algorithm beyond OpenCL requires you to study in intimate detail every aspect of a GPU's architecture. Followed by planning and development of how to best use it's resources.  When your working with bare metal your not dependent on AMD compiler optimizations which are rarely the most efficient.  Vulkan is an excellent choice for close to metal GPU manipulation.  Or if you prefer to code in native C++ then HCC is probably the best option.  I hope that helps.

**Comment by jch9678** [comment]
@DominiLux Yes, thank you, that does clarify things.  I'm following your repositories if for nothing else than to see your results.
