### ISSUE TITLE
Update instructions for amdgpu-pro

### ISSUE THREAD

**Issue by magick777** [genesismining/sgminer-gm#5]
Running ./configure as per instructions fails to find OpenCL on an Ubuntu 16.04.1 system with the current amdgpu-pro Linux driver. The following solves it:

CFLAGS="-O2 -march=native -std=gnu99 -I/opt/AMDAPPSDK-3.0/include/" LDFLAGS="-rdynamic -L/opt/amdgpu-pro/lib/x86_64-linux-gnu" ./configure

Presumably it would be trivial to add a check for amdgpu-pro into the configure script to avoid complicating the install instructions (and for the 'just works' factor).

**Comment by OhGodAGirl** [comment]
Done!
