### ISSUE TITLE
sgminer OSX Segmentation fault

### ISSUE THREAD

**Issue by yxd117** [genesismining/sgminer-gm#62]
I have compiled with the help of #54 and #56 
However, I face segmentation error when I run.
Error message.
[21:16:36] Started sgminer 5.5.5-gm-a
/Users/reset/Downloads/sgminer-gm/./kernel/wolf-skein.cl:35:29: warning: implici
t declaration of function 'amd_bitalign' is invalid in C99
        if(y < 32) return(as_ulong(amd_bitalign(x, x.s10, 32 - y)));
                            ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_
kernel.h:4274:43: note: expanded from macro 'as_ulong'
#define as_ulong( _x )  __builtin_astype( _x, ulong )
                                          ^
In file included from <program source>:7:
/Users/reset/Downloads/sgminer-gm/./kernel/wolf-skein.cl:35:20: error: invalid r
einterpretation[21:16:39] Failed to init GPU thread 3, disabling device 1
[21:16:39] thread_prepare failed for thread 3Segmentation fault: 11

**Comment by yxd117** [comment]
#54 #56

**Comment by fabulouspanda** [comment]
I got past this error by modifying cryptonight.cl as per those seen here:
https://github.com/fireice-uk/xmr-stak-amd/commit/8e26cad16012184cae1ba54573e64a1af0d04628#diff-149335197b3ff340168a92fcbf32cfe6

But there were a whole host of extra problems after that and I gave up.
