### ISSUE TITLE
SGMiner hangup on start

### ISSUE THREAD

**Issue by CreakyFaun64** [genesismining/sgminer-gm#76]
I am getting a hang up on start. I believe I am having trouble connecting to the pool, but could be mistaken. I get through all the connections but never receive any work. I will attach screenshot of command prompt and of the conf file.
Thanks for the help!
![capture1](https://user-images.githubusercontent.com/32943171/31796084-6d94ec88-b4e5-11e7-9a4a-c7daa4bc2772.PNG)
![capture2](https://user-images.githubusercontent.com/32943171/31796094-7130f846-b4e5-11e7-9046-e099da465b88.PNG)
![capture3](https://user-images.githubusercontent.com/32943171/31796097-73afd6be-b4e5-11e7-8637-2f0937221932.PNG)

**Comment by CreakyFaun64** [comment]
I attached my .bat, .conf, and the command prompt screens to show all of my work and where it is getting stuck.

**Comment by NaN-git** [comment]
Old version
