### ISSUE TITLE
CPU version only

### ISSUE THREAD

**Issue by philipperemy** [genesismining/sgminer-gm#93]
How to compile the binary with only cpu?

When I run make, I have:
```
algorithm.h:7:19: fatal error: CL/cl.h: No such file or directory
```
Which I suspect is related to AMD.

**Comment by Sjchell74** [comment]
I have little expirience bur perhaps you find good info at freebitcoin browser mining. That is simple ming software using cpu only.

**Comment by philipperemy** [comment]
I found another CPU miner that could do the job `cpuminer-opt` :)

**Comment by philipperemy** [comment]
Thanks @Sjchell74 for answering!
