### ISSUE TITLE
Stratum timeout 90 sec.

### ISSUE THREAD

**Issue by lantama70** [genesismining/sgminer-gm#95]
Hello, I am facing the problem, that I have a lot of discos when using XMR/Stratum and high Diff. The 90 seconds timeout (in combination with missing server keepalive, I think) is the problem here. Is there a possibility to avoid this? I dind't find a parameter to change the timeout in the client.....
Best
Andreas

**Comment by lantama70** [comment]
tcp-keepalive seems to have an issue. I see no communication traffic between the blocks/shares. Even when I set the paramater to a different value .......

**Comment by NaN-git** [comment]
Fixed on master. Please note that XMR requires explicit JSON keepalive messages so that --tcp-keepalive is the wrong option and --no-keepalive (default: false) is the correct one
